# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-10 10:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('webuser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfile',
            name='upload_time',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 8, 10, 10, 45, 32, 243000, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
